#!/bin/bash

LOCATION=/home/developer/repos/u2f-flask
APP=/home/developer/applications/u2f-flask
VENVDIR='venv'

git clone $LOCATION $APP

cd $APP

# Virtual Env
virtualenv $VENVDIR
source ./venv/bin/activate

pip install -r requirements.txt

# Reseting cookies
python reset_cookie_key.py

# Reseting DB
rm flaskr.db
python create_db.py

cp $APP'/hooks/'* $LOCATION'/hooks/'